// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT6uI65n8-OnnjYP7nCtbFpcYofGQ3N30',
    appId: '1:178769607471:web:1272e7f0e21bfe0d1bbfda',
    messagingSenderId: '178769607471',
    projectId: 'lexmachina-ai',
    authDomain: 'lexmachina-ai.firebaseapp.com',
    storageBucket: 'lexmachina-ai.appspot.com',
    measurementId: 'G-KLGRCL3916',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-hYZvn2Cu0Ml35ol8kEmvfdUxdrSJDYc',
    appId: '1:178769607471:android:0ef30b572aeab9721bbfda',
    messagingSenderId: '178769607471',
    projectId: 'lexmachina-ai',
    storageBucket: 'lexmachina-ai.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT6uI65n8-OnnjYP7nCtbFpcYofGQ3N30',
    appId: '1:178769607471:web:ea6148bf968569711bbfda',
    messagingSenderId: '178769607471',
    projectId: 'lexmachina-ai',
    authDomain: 'lexmachina-ai.firebaseapp.com',
    storageBucket: 'lexmachina-ai.appspot.com',
    measurementId: 'G-M3LLNCN765',
  );

}